---
- name: Update DNS and NTP
  hosts: centos
  become: True

  tasks:
  - import_role:
      name: ansible-role-hosts

  - import_role:
      name: ansible-role-resolv

  - import_role:
      name: ansible-role-chronyd